[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
evm_version = "cancun"
optimizer = true
optimizer_runs = 100000
via_ir = true
ffi = false
fs_permissions = [
  { access = "read-write", path = "./broadcast" },
  { access = "read", path = "./out" }
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[fuzz]
runs = 1000

[invariant]
runs = 256
depth = 64
fail_on_revert = true